In [1]:
import numpy as np
import minimg as mg
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook

from utils import *
%matplotlib inline


In [2]:
calimg_T2_raw = np.float64(np.asarray(mg.load("./raw tiff/raw0081.tif")))#plt.imread("./raw tiff/raw0081.tif")#mg.load("./raw tiff/raw0081.tif")
calimg_T2_gt = np.float64(np.asarray(mg.load("./gt tiff/gt0081.tif")))

maskT2 = np.loadtxt("../../NUS/Canon EOS-1Ds Mark III/CHECKER/Canon1DsMkIII_0081_mask.txt", delimiter=',')
maskT2 *= 2 #размеры разные ¯\_(ツ)_/¯

T2 = fitA(get_colors_from_patches(get_clrchkr(calimg_T2_raw, maskT2), maskT2),
          get_colors_from_patches(get_clrchkr(calimg_T2_gt, maskT2), maskT2))

print("T2:\n", T2)

calimg_T1_raw = np.float64(np.asarray(mg.load("./raw tiff/raw0118.tif")))
calimg_T1_gt = np.float64(np.asarray(mg.load("./gt tiff/gt0118.tif")))

maskT1 = np.loadtxt("../../NUS/Canon EOS-1Ds Mark III/CHECKER/Canon1DsMkIII_0118_mask.txt", delimiter=',')
maskT1 *= 2

T1 = fitA(get_colors_from_patches(get_clrchkr(calimg_T1_raw, maskT1), maskT1),
          get_colors_from_patches(get_clrchkr(calimg_T1_gt, maskT1), maskT1))

print("T1:\n", T1)


T2:
 [[ 2.14452046 -0.07589909  0.09789159]
 [ 0.09577423  1.30114204 -0.4941813 ]
 [ 0.092268   -0.26003614  1.73711922]]
T1:
 [[ 1.61007702  0.08912773 -0.00591999]
 [ 0.09393846  1.17729104 -0.52626828]
 [ 0.05396781 -0.1603709   2.57844221]]
